### ISSUE TITLE
iOS developments and fix priorities for V1

### ISSUE THREAD

**Issue by HMZahir** [AsilHQ/Asil-ios#67]
- [ ] Make an IOS browser with all the features the same as Android's. 
- [ ]  Remove VPN mode. Use DNS over https in the browser. 
- [ ]  Integrate the same models as Android. Or better if possible. 
- [ ]  One KahfGuard icon for settings. 
- [ ]  Complete parity with Android in terms of UX. 
- [ ]  Add crash dump collector and send to us for analysis. 
- [ ] #66
